#pragma once

#include "executor.h"
#include "onnx_parser.h"
#include "tensor.h"
#include <cstddef>
#include <string>
#include "instgen.h"
#include <filesystem>
#include <dlfcn.h>


#define RAH_SO_STRING "librah.so"
#define RAH_APP_ID 1
#define META_APP_ID 2
/* Rah is a 48bit (6 byte) per cycle protocol */
#define RAH_WIDTH 6


namespace fs = std::filesystem;

/* Why re-invent streams?
 * stl streams do everything this does but extracting
 * a char* from them (so that it can be sent to librah)
 * leads to redundant copies. Fstream is a gentle cpp
 * wrapper around fread(), provides easy and cheap access
 * to the underlying char*.
 */
class Fstream {
  char *m_buf;
  size_t m_size;

public:
  Fstream(const std::string &filename);
  ~Fstream();
  const char *get_data() const;
  size_t get_size() const;
};

#define META_WIDTH_BITS 48
#define META_WIDTH_BYTES (META_WIDTH_BITS/8)
#define META_FIELD_WIDTH_BYTES 6
#define META_HEADER_BYTES 18 /* 6 bytes of each field * 3 total fields in header */


//#define META_SOP 0xffffffffffff
//#define META_TYPE_RESET 0x00000000
//#define META_TYPE_DISPATCH 0x00000001
//#define META_TYPE_PAYLOAD_SIZE 0x00000002
//
//#define META_CONST_DISPATCH_RAH 0x00000000 /* default */
//#define META_CONST_DISPATCH_UART 0x00000001

std::vector<char> cvt_32248(int v);

class Rah {
public:
  virtual int write(const char *data, size_t size) = 0;
  virtual int read(char *data, size_t size) = 0;
  virtual ~Rah() {
  }
  virtual int write_meta(const std::bitset<META_WIDTH_BITS> type, const std::vector<char>& data) = 0;
};

class RealRah : public Rah {
  void *m_handle;
public:
  RealRah();
  ~RealRah();
  int write(const char *data, size_t size) override;
  int read(char *data, size_t size) override;
  int write_meta(const std::bitset<META_WIDTH_BITS> type, const std::vector<char>& data) override;
};

/* Used as a dupe of rah while running gaticc on devices
 * that do not have rah (non-vaaman devices). Used by
 * the --dry-run option, mainly for debugging
 */
class FakeRah : public Rah {
  int write(const char *data, size_t size) override;
  int read(char *data, size_t size) override;
  int write_meta(const std::bitset<META_WIDTH_BITS> type, const std::vector<char>& data) override;
};

/* Like dispatch table, but reads binarized instructions and creates a table
 * of hashed values. Used by Runner that has access to the graph, to match hashed
 * values with names from which the hash was generated.
 */
class HashedDispatchTable {
  std::vector<int> tbl;
  public:
  HashedDispatchTable(const Fstream &fp);
  bool should_dispatch(const Op::LayerBase *l) const;
};

class Runner {
  TensorPool tensor_pool;
  Op::Parser *m_parser;
  const PyEngine *m_engine;

  void scan(Rah &rah);
  void device_init();
  void load_model(Rah &rah, const Fstream &fp);
  void infer_loop(Rah &rah, const Fstream &fp);
  void check_args();
  void tensor_pool_init();
  void pyengine_init();
  std::string get_run_arg();

  template <typename inputT, typename CpuOutputT, typename DeviceOutputT,
            typename OutputT>
  void run(Rah &rah, HashedDispatchTable &hdt);

  template <typename T>
  void send_input(Op::LayerBase *l, Rah &rah, const Tensor<T> *tensor, uint32_t addr);
  void receive_output(Rah &rah, Op::LayerBase *l);
  void fake_exec(Op::LayerBase *l);
  void read_uart(BinBlob &blob, int uart_baud, int expected_size);

  template <typename T>
  void receive_output_aux(const T *data,
                                  const std::vector<int> &dims, Op::LayerBase *l);

  template <typename T>
  void compare_layer(Op::LayerBase *l, const Tensor<T> *tensor, fs::path& path);

public:
  Runner(Op::Parser &parser);
  ~Runner();
};

template <typename T>
Tensor<T> *get_slice(Tensor<T>* src, std::vector<int> s) {
	std::vector<int> dd = src->get_dims();
	assert(dd.size() == 4);
	dd.at(0) = 1;
	Tensor<T> *ret = new TensorCreate<T>(dd);
	TensorSlice<T> slice(src, s);
	for (int i = 0; i < slice.size(); ++i) {
		ret->set(i, slice.at(i));
	}
	return ret;
}

/* run is a state-machine that passes through these states of execution:
 *
 * CPU-UNSENT
 *    inputs are present on the CPU, they should be passed through
 *    nodes with DEVICE == DEVICE_CPU
 * FPGA-UNSENT
 *    the first non-cpu node marks the dispatch of the outputs of
 *    the last cpu node to the FPGA. this branch is only taken
 *    once, to send the inputs to the FPGA
 * FPGA-SENT
 *    inputs meant for the FPGA have been sent and all nodes following
 *    this with DEVICE == DEVICE_FPGA should be fake executed
 * CPU-SENT
 *    after FPGA-SENT, first DEVICE_CPU node is the node that receives
 *    outputs generated by the FPGA. This node re-aligns the tensors 
 *    (if necessary) and loads the received tensor into tensor_pool 
 *    to continue rest of the execution on CPU.
 * CPU-CONTINUE
 *    all the other nodes following this are meant to be executed
 *    on CPU normally, at the end, the final output is to be sent
 *    to the pre-processing pipeline.
 */
template <typename inputT, typename CpuOutputT, typename DeviceOutputT,
          typename OutputT>
void Runner::run(Rah &rah, HashedDispatchTable &hdt) {
  auto graph = m_parser->get_graph();
  auto order = Pass::remove_dqxq(graph);
  Pass::extract_conv_true_odims(graph);
  AddressGen generator(graph);

  InstGen instgen(*m_parser);
  IOAddrTbl io_addr_tbl = instgen.get_io_addr_tbl();

  Op::RegisterAllocator allcator(m_parser->get_graph());

  Tensor<inputT> *input_image = read_model_input<inputT>(*m_engine);
  if (input_image->dims_size() <= 1) {
    log_fatal("Expects input images to be greater than 1 dimensional (N,...) got a {} dimensional "
        "image\n", input_image->dims_size());
  }
  log_info("preprocess finish\n");
  for (int i = 0; i < input_image->dims_at(0); ++i) {
    tensor_pool.free();

    Tensor<inputT> *slice {get_slice(input_image, std::vector<int>{i})};
    if (order.at(0)->input_dims != slice->get_dims()) {
      log_fatal("Expected input dims {}, got input of dimensions {}\n", order.at(0)->input_dims, slice->get_dims());
    }
    tensor_pool.set<Tensor<inputT> *>(0, slice);

    bool sent = false;
    for (Op::LayerBase *l : order) {
      assert(l->device != DEVICE_UNKNOWN);

      l->dispatch = hdt.should_dispatch(l);
      log_info("Running layer {} on {}\n", l->name, Op::get_device_name(l->device));
      if (l->device == DEVICE_CPU && sent == false) {
        l->run(tensor_pool);
      } 
      
      if (l->device == DEVICE_FPGA && sent == false) {
        using TT = Tensor<CpuOutputT>;
        TT *out = tensor_pool.get<TT *>(l->inputs.at(0));
        Op::VirtualAddress ireg = io_addr_tbl.at(l->name).first.at(0);
        uint32_t addr = generator.io_addr_from_register(ireg);
        log_info("sending input for register {}, addr is {}\n", ireg, addr);
        send_input<CpuOutputT>(l, rah, out, addr);
        sent = true;
      } 
      
      if (l->device == DEVICE_FPGA && sent == true) {
        if (l->dispatch) {
          log_info("l->dispatch {} for layer {}\n", l->dispatch, l->name.c_str());
        }
        if (l->dispatch == true) {
          log_info("receiving output\n");
          receive_output(rah, l);
          log_info("receiving output finish\n");
        } else {
          fake_exec(l);
        }
      } 
      
      if (l->device == DEVICE_CPU && sent == true) {
        l->run(tensor_pool);
        sent = false;
      }
    }
  }
}

template <typename T> void Runner::send_input(Op::LayerBase *l, Rah &rah, const Tensor<T> *tensor, uint32_t addr) {
  auto dims = tensor->get_dims();
  if (is_op_type(l, "QLinearConv")) {
    uint32_t og_aligned_size = aligned_conv_input(dims) * sizeof(T);
    uint32_t total_size_with_packets = io_tensor_packet_size(og_aligned_size);
    BinBlob blob(total_size_with_packets);
    blob.append_sa_input<T>(og_aligned_size, addr, tensor);
    blob.append_dwp_header(0, 0);
    blob.write("input_data.bin");
    log_info("start writing images to FPGA\n");
    char *aligned_data = blob.get_data();
    rah.write(aligned_data, total_size_with_packets);
  } else {
    log_fatal("cannot send input for layer of type {} - support missing\n", l->op_type());
  }
  log_info("finish writing images to FPGA\n");
}

template <typename T>
void unalign_sa_output(Tensor<T> *tensor, const T *data) {
  /* TODO: explain this function in detail */

  auto dims = tensor->get_dims();
  auto new_dims = aligned_conv_output_dims(tensor->get_dims()); 

  if (dims[TENSOR_4D_BATCH] != 1) {
    log_fatal("can only operate on batch size 1; support must be added for more\n");
  }
  auto sa_arch = get_sa_arch();
  /* elements per column */
  int epcol = ACC_SIZE / 8;
  /* elements emitted per cycle */
  int epcy = sa_arch[SA_ARCH_COLS];
  int chan_sz = dims[TENSOR_4D_HEIGHT] * dims[TENSOR_4D_WIDTH];
  int new_chan_sz = new_dims[TENSOR_4D_HEIGHT] * new_dims[TENSOR_4D_WIDTH];
  int vacancy_factor = WORD_SIZE / epcy;
  /* elements in a column */
  int ecol = ceil_mod(ceil_mod(chan_sz, epcol), vacancy_factor);

  int channel_itr = new_dims[TENSOR_4D_CHANNELS] / sa_arch[SA_ARCH_N];
  int elements_itr = ecol / epcol;
  int data_index = 0;

  /* is out of bounds */
  auto oob = [&dims, chan_sz](int ci, int ei) -> bool {
    if (ci >= dims[TENSOR_4D_CHANNELS]) {
      return true;
    }
    if (ei >= chan_sz) {
      return true;
    }
    return false;
  };

  for (int i = 0; i < channel_itr; ++i) {
    for (int j = 0; j < elements_itr; ++j) {
      for (int k = 0; k < sa_arch[SA_ARCH_N]; ++k) {
        for (int l = 0; l < epcol; ++l) {
          int chan_index = i * sa_arch[SA_ARCH_N] + k;
          int elem_index = j * epcol + l;
          int windex = chan_index * chan_sz + elem_index;
          if (!oob(chan_index, elem_index)) {
            tensor->set(windex, data[data_index++]);
          }
          //std::cout << "chan: " << chan_index << " elem: " << elem_index
          //<< " dindex: " << data_index++ << " windex " << windex << " oob "
          //<< oob(chan_index, elem_index) << '\n';
        }
      }
    }
  }
}

template <typename T>
void unalign_va_output(Tensor<T> *tensor, const T *data) {
  auto dims = tensor->get_dims();
  size_t size = prod(dims.begin(), dims.end(), 1);
  for (int i = 0; i < size; ++i) {
    T v = data[i];
    tensor->set(i, v);
  }
}

/* Converts a byte stream into a tensor and un-aligns if if necessary */
template <typename T>
void Runner::receive_output_aux(const T *data,
                                const std::vector<int> &dims, Op::LayerBase *l) {
  static_assert(std::is_same<T, int8_t>() || std::is_same<T, uint8_t>());
  
  std::vector<int> odims;
  if (strcmp(l->op_type(), "QLinearConv") == 0) {
    Op::Layer::QLinearConv *qc = dynamic_cast<Op::Layer::QLinearConv *>(l);
    if (qc->pipelined_output_dims.size() != 0) {
      odims = qc->pipelined_output_dims;
    }
  } else {
    odims = l->output_dims;
  }

  Tensor<T> *tensor = new TensorCreate<T>(odims);
  if (strcmp(l->op_type(), "QLinearConv") == 0) {
    unalign_sa_output(tensor, data);
  } else if (strcmp(l->op_type(), "QGemm") == 0) {
    unalign_va_output(tensor, data);
  } else {
    log_fatal("cant handle un-alignment for layer of type {}\n", l->op_type());
  }

  if (tensor_pool.has_value(l->outputs.at(0))) {
    tensor_pool.free(l->outputs.at(0));
  }
  tensor_pool.set<Tensor<T> *>(l->outputs.at(0), tensor);

  if (l->dispatch) {
  	write_model_output<T>(*m_engine, tensor);
  }
  if (gbl_args.has_option("compare-layer")) {
    std::string arg = gbl_args["compare-layer"].as<std::string>();
    fs::path p {fs::path(arg)};
    fs::path abs_p = fs::absolute(p);
    compare_layer(l, tensor, abs_p);
  }
}

template <typename T>
T get_dlsym(void *m_handle, std::string func_name) {
  T fn;
  fn = (T) dlsym(m_handle, func_name.c_str());
  char *error = dlerror();
  if (error != NULL) {
    log_fatal("dlsym: {}\n", error);
  }
  return fn;
}


template <typename T>
void Runner::compare_layer(Op::LayerBase *l, const Tensor<T> *tensor, fs::path& file) {
  //fs::path file = path / fs::path(l->name + ".tensor.npy"); 
  if (!fs::exists(file)) {
    log_fatal("{}: no such file or directory\n", file);
  }
  PyObject *received_tensor = t2np<T>(tensor);
  PyObject *args = Py_BuildValue("(Os)", received_tensor, file.c_str());
  log_info("Comparing {} with {}\n", l->name, file);
  m_engine->call_func("compare_npy", args);
}
