#pragma once

#include "executor.h"
#include "onnx_parser.h"
#include "tensor.h"
#include <cstddef>
#include <string>
#include "instgen.h"

#define RAH_SO_STRING "librah.so"
#define RAH_APP_ID 1

/* Why re-invent streams?
 * stl streams do everything this does but extracting
 * a char* from them (so that it can be sent to librah)
 * leads to redundant copies. Fstream is a gentle cpp
 * wrapper around fread(), provides easy and cheap access
 * to the underlying char*.
 */
class Fstream {
  char *m_buf;
  size_t m_size;

public:
  Fstream(const std::string &filename);
  ~Fstream();
  const char *get_data() const;
  size_t get_size() const;
};

class Rah {
  void *m_handle;

public:
  Rah();
  ~Rah();
  int write(const char *data, size_t size);
  int read(char *data, size_t size);
};

/* Like dispatch table, but reads binarized instructions and creates a table
 * of hashed values. Used by Runner that has access to the graph, to match hashed
 * values with names from which the hash was generated.
 */
class HashedDispatchTable {
  std::vector<int> tbl;
  public:
  HashedDispatchTable(const Fstream &fp);
  bool should_dispatch(const Op::LayerBase *l) const;
};

class Runner {
  TensorPool tensor_pool;
  void scan();
  void device_init();
  void load_model(Rah &rah, const Fstream &fp);
  void infer_loop(Rah &rah, const Fstream &fp, PyEngine &engine, const Op::Parser &parser);
  void check_args();
  void tensor_pool_init(const Op::Parser &parser);
  PyEngine create_pyengine();
  std::string get_run_arg();

  template <typename inputT, typename CpuOutputT, typename DeviceOutputT,
            typename OutputT>
  void run(Rah &rah, HashedDispatchTable &hdt, PyEngine &engine, const Op::Parser &parser);

  template <typename T>
  void send_input(Rah &rah, const Tensor<T> *tensor, uint32_t addr);
  void receive_output(Rah &rah, Op::LayerBase *l);
  void fake_exec(Op::LayerBase *l);

public:
  Runner(const Op::Parser &parser);
};

/* run is a state-machine that passes through these states of execution:
 *
 * CPU-UNSENT
 *    inputs are present on the CPU, they should be passed through
 *    nodes with DEVICE == DEVICE_CPU
 * FPGA-UNSENT
 *    the first non-cpu node marks the dispatch of the outputs of
 *    the last cpu node to the FPGA. this branch is only taken
 *    once, to send the inputs to the FPGA
 * FPGA-SENT
 *    inputs meant for the FPGA have been sent and all nodes following
 *    this with DEVICE == DEVICE_FPGA should be fake executed
 * CPU-SENT
 *    after FPGA-SENT, first DEVICE_CPU node is the node that receives
 *    outputs generated by the FPGA. This node re-aligns the tensors 
 *    (if necessary) and loads the received tensor into tensor_pool 
 *    to continue rest of the execution on CPU.
 * CPU-CONTINUE
 *    all the other nodes following this are meant to be executed
 *    on CPU normally, at the end, the final output is to be sent
 *    to the pre-processing pipeline.
 */
template <typename inputT, typename CpuOutputT, typename DeviceOutputT,
          typename OutputT>
void Runner::run(Rah &rah, HashedDispatchTable &hdt, PyEngine &engine, const Op::Parser &parser) {
  Tensor<inputT> *input_image = read_model_input<inputT>(engine);
  log_info("preprocess finish");

  auto graph = parser.get_graph();
  auto order = Pass::remove_dqxq(graph);
  AddressGen generator(graph);

  tensor_pool.set<Tensor<inputT> *>(0, input_image);

  bool sent = false;
  for (Op::LayerBase *l : order) {
    assert(l->device != DEVICE_UNKNOWN);

    l->dispatch = hdt.should_dispatch(l);
    log_info("Running layer %s on %s", l->name.c_str(),
               get_device_name(l->device));
    if (l->device == DEVICE_CPU && sent == false) {
      l->run(tensor_pool);
    } else if (l->device == DEVICE_FPGA && sent == false) {
      using TT = Tensor<CpuOutputT>;
      TT *out = tensor_pool.get<TT *>(l->inputs.at(0));
      uint32_t addr = generator.io_addr_from_register(l->inputs.at(0));
      send_input<CpuOutputT>(rah, out, addr);
      sent = true;
      exit(1);
    } else if (l->device == DEVICE_FPGA && sent == true) {
      if (l->dispatch == true) {
        receive_output(rah, l);
      } else {
        fake_exec(l);
      }
    } else if (l->device == DEVICE_CPU && sent == true) {
      // receive output - rah read stuff
      sent = false;
    }
  }
}

template <typename T> void Runner::send_input(Rah &rah, const Tensor<T> *tensor, uint32_t addr) {
  auto dims = tensor->get_dims();
  /* start and end DWP_HEADER */
  uint32_t aligned_size = aligned_conv_input(dims) + (DWP_HEADER_BYTES * 2) + 1;
  BinBlob blob(aligned_size);
  blob.append_sa_input<T>(aligned_size, addr, tensor);
  blob.append_dwp_header(0, 0);
  log_info("start writing images to FPGA");
  // rah.write(aligned_data, aligned_size);
  log_info("finish writing images to FPGA");
}

