#pragma once

#include "executor.h"
#include "onnx_parser.h"
#include "tensor.h"
#include <cstddef>
#include <string>
#include "instgen.h"

#define RAH_SO_STRING "librah.so"
#define RAH_APP_ID 1

/* Why re-invent streams?
 * stl streams do everything this does but extracting
 * a char* from them (so that it can be sent to librah)
 * leads to redundant copies. Fstream is a gentle cpp
 * wrapper around fread(), provides easy and cheap access
 * to the underlying char*.
 */
class Fstream {
  char *m_buf;
  size_t m_size;

public:
  Fstream(const std::string &filename);
  ~Fstream();
  const char *get_data() const;
  size_t get_size() const;
};

class Rah {
  void *m_handle;

public:
  Rah();
  ~Rah();
  int write(const char *data, size_t size);
  int read(char *data, size_t size);
};

/* Like dispatch table, but reads binarized instructions and creates a table
 * of hashed values. Used by Runner that has access to the graph, to match hashed
 * values with names from which the hash was generated.
 */
class HashedDispatchTable {
  std::vector<int> tbl;
  public:
  HashedDispatchTable(const Fstream &fp);
  bool should_dispatch(const Op::LayerBase *l) const;
};

class Runner {
  TensorPool tensor_pool;
  void scan();
  void device_init();
  void load_model(Rah &rah, const Fstream &fp);
  void infer_loop(Rah &rah, const Fstream &fp, PyEngine &engine, const Op::Parser &parser);
  void check_args();
  void tensor_pool_init(const Op::Parser &parser);
  PyEngine create_pyengine();
  std::string get_run_arg();

  template <typename inputT, typename CpuOutputT, typename DeviceOutputT,
            typename OutputT>
  void run(Rah &rah, HashedDispatchTable &hdt, PyEngine &engine, const Op::Parser &parser);

  template <typename T>
  void send_input(Rah &rah, const Tensor<T> *tensor, uint32_t addr);
  void receive_output(Rah &rah, Op::LayerBase *l);
  void fake_exec(Op::LayerBase *l);

  template <typename T>
  void receive_output_aux(const unsigned char *data,
                                  const std::vector<int> &dims, Op::LayerBase *l);

public:
  Runner(const Op::Parser &parser);
};

/* run is a state-machine that passes through these states of execution:
 *
 * CPU-UNSENT
 *    inputs are present on the CPU, they should be passed through
 *    nodes with DEVICE == DEVICE_CPU
 * FPGA-UNSENT
 *    the first non-cpu node marks the dispatch of the outputs of
 *    the last cpu node to the FPGA. this branch is only taken
 *    once, to send the inputs to the FPGA
 * FPGA-SENT
 *    inputs meant for the FPGA have been sent and all nodes following
 *    this with DEVICE == DEVICE_FPGA should be fake executed
 * CPU-SENT
 *    after FPGA-SENT, first DEVICE_CPU node is the node that receives
 *    outputs generated by the FPGA. This node re-aligns the tensors 
 *    (if necessary) and loads the received tensor into tensor_pool 
 *    to continue rest of the execution on CPU.
 * CPU-CONTINUE
 *    all the other nodes following this are meant to be executed
 *    on CPU normally, at the end, the final output is to be sent
 *    to the pre-processing pipeline.
 */
template <typename inputT, typename CpuOutputT, typename DeviceOutputT,
          typename OutputT>
void Runner::run(Rah &rah, HashedDispatchTable &hdt, PyEngine &engine, const Op::Parser &parser) {
  Tensor<inputT> *input_image = read_model_input<inputT>(engine);
  log_info("preprocess finish");

  auto graph = parser.get_graph();
  auto order = Pass::remove_dqxq(graph);
  AddressGen generator(graph);

  InstGen instgen(parser);
  IOAddrTbl io_addr_tbl = instgen.get_io_addr_tbl();

  Op::RegisterAllocator allcator(parser.get_graph());

  tensor_pool.set<Tensor<inputT> *>(0, input_image);

  bool sent = false;
  for (Op::LayerBase *l : order) {
    assert(l->device != DEVICE_UNKNOWN);

    l->dispatch = hdt.should_dispatch(l);
    log_info("Running layer %s on %s", l->name.c_str(),
               get_device_name(l->device));
    if (l->device == DEVICE_CPU && sent == false) {
      l->run(tensor_pool);
    } 
    
    if (l->device == DEVICE_FPGA && sent == false) {
      using TT = Tensor<CpuOutputT>;
	  tensor_pool.print();
      TT *out = tensor_pool.get<TT *>(l->inputs.at(0));
      Op::VirtualAddress ireg = io_addr_tbl.at(l->name).first.at(0);
      uint32_t addr = generator.io_addr_from_register(ireg);
      log_info("sending input for register %d, addr is %d", ireg, addr);
      send_input<CpuOutputT>(rah, out, addr);
      sent = true;
    } 
    
    if (l->device == DEVICE_FPGA && sent == true) {
      std::cout << "l->dispatch " << l->dispatch << " for layer " << l->name << '\n';
      if (l->dispatch == true) {
        log_info("receiving output");
        receive_output(rah, l);
        log_info("receiving output finish");
      } else {
        log_info("fake exec started");
        fake_exec(l);
        log_info("fake exec started finish");
      }
    } 
    
    if (l->device == DEVICE_CPU && sent == true) {
      l->run(tensor_pool);
      sent = false;
    }
  }
}

template <typename T> void Runner::send_input(Rah &rah, const Tensor<T> *tensor, uint32_t addr) {
  auto dims = tensor->get_dims();

  uint32_t og_aligned_size = aligned_conv_input(dims) * sizeof(T);
  uint32_t total_size_with_packets= io_tensor_packet_size(og_aligned_size);

  BinBlob blob(total_size_with_packets);
  blob.append_sa_input<T>(og_aligned_size, addr, tensor);
  blob.append_dwp_header(0, 0);
  blob.write("rah_input.bin");
  log_info("start writing images to FPGA");
  char *aligned_data = blob.get_data();
  rah.write(aligned_data, total_size_with_packets);
  log_info("finish writing images to FPGA");
}

template <typename T>
void unalign_sa_output(Tensor<T> *tensor, const unsigned char *data) {
  auto dims = tensor->get_dims();
  size_t size = prod(dims.begin(), dims.end(), 1);
  auto sa_arch = get_sa_arch();
  int acc_width = ACC_SIZE/8;
  int eiec = (dims[TENSOR_4D_HEIGHT] * dims[TENSOR_4D_WIDTH]) / acc_width;
  int tensor_index = 0;
  for (int j = 0; j < dims[TENSOR_4D_CHANNELS]; ++j) {
    for (int k = 0; k < eiec; ++k) {
      for (int l = 0; l < acc_width; ++l) {
        int index = (j * acc_width) + (acc_width * sa_arch[SA_ARCH_COLS] * k) + l;
        T v = data[index];
        tensor->set(tensor_index++, v);
      }
    }
  }
}

template <typename T>
void unalign_va_output(Tensor<T> *tensor, const unsigned char *data) {
  auto dims = tensor->get_dims();
  size_t size = prod(dims.begin(), dims.end(), 1);
  for (int i = 0; i < size; ++i) {
    T v = data[i];
    tensor->set(i, v);
  }
}

/* Converts a byte stream into a tensor and un-aligns if if necessary */
template <typename T>
void Runner::receive_output_aux(const unsigned char *data,
                                const std::vector<int> &dims, Op::LayerBase *l) {
  static_assert(std::is_same<T, int8_t>() || std::is_same<T, uint8_t>());
  
  print_vec("expected dims", dims);
  print_vec("input dims", l->input_dims);
  print_vec("input dims", l->output_dims);

  Tensor<T> *tensor = new TensorCreate<T>(l->output_dims);
  if (strcmp(l->op_type(), "QLinearConv") == 0) {
    unalign_sa_output(tensor, data);
  } else if (strcmp(l->op_type(), "QGemm") == 0) {
    unalign_va_output(tensor, data);
  } else {
    log_fatal("cant handle un-alignment for layer of type %s", l->op_type());
  }

  if (tensor_pool.has_value(l->outputs.at(0))) {
    tensor_pool.free(l->outputs.at(0));
  }
  tensor_pool.set<Tensor<T> *>(l->outputs.at(0), tensor);
}

template <typename T>
T get_dlsym(void *m_handle, std::string func_name) {
  T fn;
  fn = (T) dlsym(m_handle, func_name.c_str());
  char *error = dlerror();
  if (error != NULL) {
    log_fatal("dlsym: %s", error);
  }
  return fn;
}

